.github: Use ubuntu-20.04 instead of ubuntu-latest
"ubuntu-latest" is now 22.04, and the GitHub Actions fail for Python 2.7
and 3.6:

> Run actions/setup-python@v2
> Version 3.6 was not found in the local cache
> Error: Version 3.6 with arch x64 not found
> The list of all available versions can be found here:
> https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json