requirements.txt: Don't lock flask version
It was incompatible with some recent jinja2 version, which we weren't
specifying:

> >   from jinja2 import escape
> E   ImportError: cannot import name 'escape' from 'jinja2'
> /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/
>   flask/__init__.py:14: ImportError

If I lock jinja2 to 2.10.1 (to match Ubuntu 20.04, which has flask
1.1.1) then there's some other error with the `markupsafe` dependency.
I expect flask cares about backwards compatibility so this will
hopefully work.